### ISSUE TITLE
Переход на NetStandard 2.0

### ISSUE THREAD

**Issue by mustiks** [petrovich/petrovich-net#17]
Хочу перетащить проект на NetStandard 2.0 и за одно сделать отчества необязательным а это breaking change, возможно еще уйти от yaml на чисто json, собственно 2 вопроса:
1) Отдельным портом или версия 2.0?
2) Возражения?

**Comment by mikhail-barg** [comment]
Посмотрите на https://github.com/mikhail-barg/petrovich-net-lite, там у меня как раз второй стандарт и json )
