### ISSUE TITLE
Автоопределение пола по отчеству

### ISSUE THREAD

**Issue by UnstableMutex** [petrovich/petrovich-net#6]
есть еще ньюанс в определении пола по отчеству. У некоторых национальностей есть приставки Оглы и Кызы что значит соответственно сын и дочь. Пример:
Иногда приставки пишутся через тире иногда через пробел

![image](https://cloud.githubusercontent.com/assets/5594562/3887091/d2779e34-21ea-11e4-991e-27742b3cea87.png)

![image](https://cloud.githubusercontent.com/assets/5594562/3887125/76a2b7aa-21eb-11e4-92b7-0cda61d66cdb.png)

**Comment by mustiks** [comment]
Учтено
